### ISSUE TITLE
Do you use crawler?

### ISSUE THREAD

**Issue by tengerye** [skrish13/ml-contests-conf#5]
Hi, thanks for your great contribution. It is exactly what I needed.

1. Do you use the crawler to automatically get the information of competitions? If not, it will help a lot, I think.
2. [ICDAR](https://icdar2021.org/) holds competitions annually. It is the top conference for document analysis and recognition field (and it is focus on the field) only. I strongly recommend to add it as well.

**Comment by skrish13** [comment]
I currently do it manually since I'm interested in conferences like CVPR/ICCV etc. But, crawler could be really useful to scale this up. Sure, I will try to add ICDAR when I get time. Hopefully, people contribute to cover more conferences' competitions.

**Comment by tengerye** [comment]
@skrish13 If you could provide detailed way of searching related information, and is willing to adapt a crawler, I am willing to help.
